services:
  app-java:
    build: ./app-java
    container_name: app-java
    ports:
      - 8080:8080
    networks:
      - app-net
    volumes:
      - gradle-cache:/root/.gradle
networks:
  app-net:
    driver: bridge
volumes:
  gradle-cache:
    driver: local
