services:
  app-java:
    build: ./app-java
    container_name: app-java
    environment:
      - MYSQL_HOST=app-mysql
    ports:
      - 8080:8080
    networks:
      - app-net
  #app-ui:
   # build: ./app-ui
    #container_name: app-ui
    #environment:
    #  - API_HOST=app-java
    #ports:
    #  - 80:80
    #networks:
    #  - app-net
  app-mysql:
    image: mysql:8.1.0
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    networks:
      - app-net
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  app-net:
    driver: bridge
volumes:
  mysql-data:
    driver: local
