name: main-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  docker-compose-build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build And Run
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
